
spring:
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12788181
    username: sql12788181
    password: a2B8HhtBbU
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
